import Image from "next/image";
import Link from "next/link";
import { BUSINESS, services } from "../lib/business";
import EmailLink from "./email-link";

const logoUrl = "/us-flooring-header-logo-400x160.png";
const pages = [["/", "Home"], ["/products", "Products & Services"], ["/about", "About"], ["/gallery", "Gallery"], ["/reviews", "Reviews"], ["/contact", "Free Estimate"], ["/buyers-guide", "Buyer’s Guide"]] as const;

export default function Footer() { return <footer className="site-footer"><div className="container footer-grid"><div><Image src={logoUrl} alt="US Flooring & Molding — Burbank, CA" width={200} height={80} sizes="200px" className="footer-logo" /><p>Family-owned flooring store and contractor in Burbank, California. More than 20 years in the trade — every floor treated like it&apos;s going in our own home.</p><div className="footer-social"><a href="https://www.yelp.com/biz/us-flooring-and-molding-burbank" target="_blank" rel="noopener noreferrer">View us on Yelp</a><a href={BUSINESS.linkedInUrl} target="_blank" rel="noopener noreferrer">Connect on LinkedIn</a></div></div><div><h2>Pages</h2><nav aria-label="Footer navigation"><ul>{pages.map(([href, label]) => <li key={href}><Link href={href}>{label}</Link></li>)}</ul></nav></div><div><h2>Services</h2><nav aria-label="Services navigation"><ul>{services.map(([label, href]) => <li key={href}><Link href={href}>{label}</Link></li>)}</ul></nav></div><div><h2>Contact</h2><address><a href={`tel:${BUSINESS.phone}`}>{BUSINESS.phoneDisplay}</a><EmailLink /><a href={BUSINESS.googleMapsUrl} target="_blank" rel="noopener noreferrer">{BUSINESS.address.street}<br />{BUSINESS.address.city}, {BUSINESS.address.state} {BUSINESS.address.zip}</a></address><Link href="/contact" className="button">Get Free Estimate</Link></div></div><div className="footer-bottom container"><span>© 2026 {BUSINESS.legalName} All rights reserved.</span><Link href="/privacy">Privacy Policy</Link><a href={BUSINESS.googleMapsUrl} target="_blank" rel="noopener noreferrer">View on Google Maps</a><span>Family Flooring. Honest People. Floors Built to Last.</span></div></footer>; }
